### ISSUE TITLE
markbot-screenshot-accessibility

### ISSUE THREAD

**Issue by emfeather94** [emfeather94/accessibility-fixer-upper#1]
Sorry to bug you again - here is the screenshot for as far as I could get with the fixer-upper assignment!

<img width="1680" alt="fixerupper-featherstone" src="https://user-images.githubusercontent.com/55094092/79816720-dd808b00-8351-11ea-9fd8-3397fb67e09b.png">

Emily

@muxlowc

**Comment by muxlowc** [comment]
@emfeather94  awesome, the only thing is the first issue - if you go to line 15, just make sure you delete the text-decoration: none - this is removing the underline, but links should always be underlined to be accessible 

Otherwise, looks good - I'll go and give you the mark due to weird screenshot issues!

**Comment by emfeather94** [comment]
aha! I was just turning it on and off. I see now - thanks!
